service: serverlesswp-wordpress-starter

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    payload: '2.0'

functions:
  requestHandler:
    handler: api/index.handler
    memorySize: 1024
    timeout: 15
    events:
      - httpApi:
          method: any
          path: /{proxy+}
    environment:
      DATABASE: 'postgresql://postgres.cfbemsfwvjpykoqtfypl:HP3xOhy8D9sX1b3c@aws-0-us-west-1.pooler.supabase.com:6543/postgres'
      USERNAME: ''
      PASSWORD: HP3xOhy8D9sX1b3c
      HOST: ''